SET SQLBLANKLINES ON
CREATE TABLE CLIENTE 
(
  ID_CLIENTE VARCHAR(6) NOT NULL 
, CEDULA NUMERIC(9) NOT NULL 
, NOMBRE VARCHAR(30) NOT NULL 
, DIRECCION VARCHAR(30) DEFAULT 'Sin direccion' NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE DEFAULT getdate() NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE DEFAULT getdate() NOT NULL 
, CONSTRAINT PK_CLIENTE PRIMARY KEY 
  (
    ID_CLIENTE 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CLIENTE_PK ON CLIENTE (ID_CLIENTE ASC) 
  )
  ENABLE 
);

CREATE TABLE EMPLEADO 
(
  ID_EMPLEADO VARCHAR(6) NOT NULL 
, CEDULA NUMERIC(9) NOT NULL 
, FECHA_INGRESO DATE DEFAULT getdate() NOT NULL 
, NOMBRE VARCHAR(20) NOT NULL 
, TELEFONO NUMERIC(8) NOT NULL 
, DIRECCION VARCHAR(50) DEFAULT 'Sin direccion' NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE DEFAULT getdate() NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE DEFAULT getdate() NOT NULL 
, CONSTRAINT PK_EMPLEADO PRIMARY KEY 
  (
    ID_EMPLEADO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX EMPLEADO_PK ON EMPLEADO (ID_EMPLEADO ASC) 
  )
  ENABLE 
);

CREATE TABLE MATERIAL 
(
  CODIGO VARCHAR(6) NOT NULL 
, DESCRIPCION VARCHAR(40) DEFAULT 'Sin descripcion' NOT NULL 
, U_COSTO_COLONES NUMERIC(9) NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE DEFAULT GETDATE() NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE DEFAULT GETDATE() NOT NULL 
, CONSTRAINT MATERIAL_PK PRIMARY KEY 
  (
    CODIGO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX MATERIAL_AD_PK ON MATERIAL (CODIGO ASC) 
  )
  ENABLE 
);

CREATE TABLE PROVEEDOR 
(
  ID_PROVEEDOR VARCHAR(6) NOT NULL 
, NBR_PROVEEDOR VARCHAR(30) NOT NULL 
, DIRECCION VARCHAR(50) DEFAULT 'Sin direccion' NOT NULL 
, CEDULA NUMERIC(9) NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE DEFAULT getdate() NOT NULL 
, ID_U_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE DEFAULT GETDATE() NOT NULL 
, CONSTRAINT PK_PROVEEDOR PRIMARY KEY 
  (
    ID_PROVEEDOR 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PROVEEDOR_PK ON PROVEEDOR (ID_PROVEEDOR ASC) 
  )
  ENABLE 
);

CREATE TABLE PROYECTO 
(
  ID_PROYECTO VARCHAR(8) NOT NULL 
, DESCRIPCION VARCHAR(40) DEFAULT 'Sin descripcion' NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE NOT NULL 
, CONSTRAINT PK_PROYECTO PRIMARY KEY 
  (
    ID_PROYECTO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PROYECTO_PK ON PROYECTO (ID_PROYECTO ASC) 
  )
  ENABLE 
);

CREATE TABLE SERVICIO 
(
  CODIGO VARCHAR(6) NOT NULL 
, DESCRIPCION VARCHAR2(40) DEFAULT 'Sin Descripcion' NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE DEFAULT getdate() NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE DEFAULT getdate() NOT NULL 
, CONSTRAINT PK_SERVICIO PRIMARY KEY 
  (
    CODIGO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SERVICIOS_AD_PK ON SERVICIO (CODIGO ASC) 
  )
  ENABLE 
);

CREATE TABLE CLIENTE_EMAIL 
(
  CORREO VARCHAR(30) NOT NULL 
, ID_CLIENTE VARCHAR(6) NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE DEFAULT getdate() NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE DEFAULT getdate() NOT NULL 
, CONSTRAINT CLIENTE_EMAIL_PK PRIMARY KEY 
  (
    CORREO 
  )
  ENABLE 
);

CREATE TABLE CLIENTE_TELEFONO 
(
  TELEFONO NUMERIC(8) NOT NULL 
, ID_CLIENTE VARCHAR(6) NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE NOT NULL 
, CONSTRAINT PK_CLIENTE_TELEFONO PRIMARY KEY 
  (
    TELEFONO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CLIENTE_TELEFONO_PK ON CLIENTE_TELEFONO (TELEFONO ASC) 
  )
  ENABLE 
);

CREATE TABLE HORAS_TRABAJADAS 
(
  ID_PROYECTO VARCHAR(8) NOT NULL 
, CANTIDAD_DE_HORAS NUMERIC(6) DEFAULT 1 NOT NULL 
, QUINCENA DATE NOT NULL 
, ESTADO CHAR(1) DEFAULT 'P' NOT NULL 
, ID_EMPLEADO VARCHAR(6) NOT NULL 
, SALARIO_HORA NUMERIC(10) NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE DEFAULT getdate() NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE DEFAULT getdate() NOT NULL 
);

CREATE TABLE LOGIN 
(
  LOGIN VARCHAR(6) NOT NULL 
, ID_EMPLEADO VARCHAR(6) NOT NULL 
, PASSWORD VARCHAR(20) NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE DEFAULT getdate() NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE DEFAULT getdate() NOT NULL 
, CONSTRAINT PK_LOGIN PRIMARY KEY 
  (
    LOGIN 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX LOGIN_PK ON LOGIN (LOGIN ASC) 
  )
  ENABLE 
);

CREATE TABLE MAT_PROVEEDOR 
(
  ID_PROVEEDOR VARCHAR(6) NOT NULL 
, CODIGO VARCHAR(6) NOT NULL 
, CODIGO_MAT_PROV VARCHAR(10) NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE NOT NULL 
, CONSTRAINT PK_MAT_PROVEEDOR PRIMARY KEY 
  (
    CODIGO 
  , ID_PROVEEDOR 
  , CODIGO_MAT_PROV 
  )
  ENABLE 
);

CREATE TABLE PROVEEDOR_EMAIL 
(
  CORREO VARCHAR(50) NOT NULL 
, ID_PROVEEDOR VARCHAR(6) NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE NOT NULL 
, CONSTRAINT PK_EMAIL PRIMARY KEY 
  (
    CORREO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX EMAIL_PK ON PROVEEDOR_EMAIL (CORREO ASC) 
  )
  ENABLE 
);

CREATE TABLE PROVEEDOR_TELEFONO 
(
  TELEFONO NUMERIC(8) NOT NULL 
, ID_PROVEEDOR VARCHAR(6) NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE NOT NULL 
, CONSTRAINT PK_TELEFONO_PROVEEDOR PRIMARY KEY 
  (
    TELEFONO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX TELEFONO_PROVEEDOR_PK ON PROVEEDOR_TELEFONO (TELEFONO ASC) 
  )
  ENABLE 
);

CREATE TABLE CONTRATO 
(
  ID_CONTRATO VARCHAR(6) NOT NULL 
, ID_CLIENTE VARCHAR(6) NOT NULL 
, ID_PROYECTO VARCHAR(8) NOT NULL 
, PLAZO_MESES NUMERIC(6) NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE NOT NULL 
, CONSTRAINT PK_CONTRATO PRIMARY KEY 
  (
    ID_CONTRATO 
  )
  ENABLE 
);

CREATE TABLE EMPLEADO_PROYECTO 
(
  ID_PROYECTO VARCHAR(8) NOT NULL 
, ID_EMPLEADO VARCHAR(6) NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE NOT NULL 
, CONSTRAINT PK_EMP_PRY PRIMARY KEY 
  (
    ID_EMPLEADO 
  , ID_PROYECTO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX EMPLEADOPROYECTO_PK ON EMPLEADO_PROYECTO (ID_EMPLEADO ASC, ID_PROYECTO ASC) 
  )
  ENABLE 
);

CREATE TABLE FACTURA 
(
  ID_FACTURA VARCHAR(6) NOT NULL 
, ID_PROVEEDOR VARCHAR(6) NOT NULL 
, ID_PROYECTO VARCHAR(8) NOT NULL 
, MONTO_TOTAL NUMERIC(10) NOT NULL 
, SALDO_PENDIENTE NUMERIC(10) NOT NULL 
, FECHA_FACTURA DATE NOT NULL 
, FECHA_VENCIMIENTO DATE NOT NULL 
, QUINCENA DATE NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE NOT NULL 
, CONSTRAINT PK_FACTURA PRIMARY KEY 
  (
    ID_FACTURA 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX FACTURA_PK ON FACTURA (ID_FACTURA ASC) 
  )
  ENABLE 
);

CREATE TABLE PROYECTO_SUPERVISOR 
(
  FECHA_INICIO DATE NOT NULL 
, ID_EMPLEADO VARCHAR(6) NOT NULL 
, ID_PROYECTO VARCHAR(8) NOT NULL 
, FECHA_FINAL DATE DEFAULT 2020-12-31 NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE DEFAULT GetDate() NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE DEFAULT GetDate() NOT NULL 
, CONSTRAINT PROYECTO_SUPERVISOR_PK PRIMARY KEY 
  (
    FECHA_INICIO 
  , ID_EMPLEADO 
  )
  ENABLE 
);

CREATE TABLE SERV_PROVEEDOR 
(
  ID_PROVEEDOR VARCHAR(6) NOT NULL 
, CODIGO VARCHAR(6) NOT NULL 
, CODIGO_SERV_PROV VARCHAR(10) NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE DEFAULT getdate() NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE DEFAULT getdate() NOT NULL 
, CONSTRAINT PK_PROV_SERVICIO PRIMARY KEY 
  (
    CODIGO 
  , ID_PROVEEDOR 
  , CODIGO_SERV_PROV 
  )
  ENABLE 
);

CREATE TABLE CUENTAS_POR_COBRAR 
(
  ID_CONTRATO VARCHAR(6) NOT NULL 
, ESTADO CHAR(1) NOT NULL 
, MONTO_TOTAL NUMERIC(10) NOT NULL 
, MONTO_PAGADO NUMERIC(10) NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE NOT NULL 
, CONSTRAINT CUENTA_PK PRIMARY KEY 
  (
    ID_CONTRATO 
  )
  ENABLE 
);

CREATE TABLE LINEA_FACTURA 
(
  ID_FACTURA VARCHAR(6) NOT NULL 
, ID_LINEA VARCHAR(6) NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE NOT NULL 
, CONSTRAINT PK_LINEA_FACTURA PRIMARY KEY 
  (
    ID_FACTURA 
  , ID_LINEA 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX LINEA_FACTURA_PK ON LINEA_FACTURA (ID_FACTURA ASC, ID_LINEA ASC) 
  )
  ENABLE 
);

CREATE TABLE L_MAT_PROVEEDOR 
(
  CODIGO VARCHAR(6) NOT NULL 
, ID_FACTURA VARCHAR(6) NOT NULL 
, ID_LINEA VARCHAR(6) NOT NULL 
, ID_PROVEEDOR VARCHAR(6) NOT NULL 
, CANTIDAD NUMERIC(6) NOT NULL 
, COSTO_UNITARIO NUMERIC(10) NOT NULL 
, UNIDAD_MEDIDA CHAR(5) NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE NOT NULL 
, CONSTRAINT PK_L_MAT_PROVEEDOR PRIMARY KEY 
  (
    ID_FACTURA 
  , ID_LINEA 
  , ID_PROVEEDOR 
  , CODIGO 
  )
  ENABLE 
);

CREATE TABLE L_SER_PROVEEDOR 
(
  CODIGO VARCHAR(6) NOT NULL 
, ID_FACTURA VARCHAR(6) NOT NULL 
, ID_LINEA VARCHAR(6) NOT NULL 
, ID_PROVEEDOR VARCHAR(6) NOT NULL 
, COSTO_UNITARIO NUMERIC(10) NOT NULL 
, CANTIDAD NUMERIC(6) NOT NULL 
, UNIDAD_MEDIDA CHAR(4) NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE NOT NULL 
, CONSTRAINT PK_L_SER_PROVEEDOR PRIMARY KEY 
  (
    ID_PROVEEDOR 
  , ID_LINEA 
  , ID_FACTURA 
  , CODIGO 
  )
  ENABLE 
);

ALTER TABLE CLIENTE
ADD CONSTRAINT UK_CLNT_CEDULA UNIQUE 
(
  CEDULA 
)
USING INDEX 
(
    CREATE UNIQUE INDEX CLIENTE_UK1 ON CLIENTE (CEDULA ASC) 
)
 ENABLE;

ALTER TABLE EMPLEADO
ADD CONSTRAINT UK_CEDULA UNIQUE 
(
  CEDULA 
)
USING INDEX 
(
    CREATE UNIQUE INDEX EMPLEADO_UK1 ON EMPLEADO (CEDULA ASC) 
)
 ENABLE;

ALTER TABLE LINEA_FACTURA
ADD CONSTRAINT LINEA_ID_FACTURA UNIQUE 
(
  ID_FACTURA 
)
USING INDEX 
(
    CREATE UNIQUE INDEX LINEA_FACTURA_UK1 ON LINEA_FACTURA (ID_FACTURA ASC) 
)
 ENABLE;

ALTER TABLE L_SER_PROVEEDOR
ADD CONSTRAINT UK_L_SER_PROVEEDOR UNIQUE 
(
  ID_LINEA 
)
USING INDEX 
(
    CREATE UNIQUE INDEX L_SER_PROVEEDOR_UK1 ON L_SER_PROVEEDOR (ID_LINEA ASC) 
)
 ENABLE;

ALTER TABLE MAT_PROVEEDOR
ADD CONSTRAINT MAT_PROVEEDOR_UK1 UNIQUE 
(
  CODIGO 
)
ENABLE;

ALTER TABLE PROVEEDOR
ADD CONSTRAINT UK_PROV_CED UNIQUE 
(
  CEDULA 
)
USING INDEX 
(
    CREATE UNIQUE INDEX PROVEEDOR_UK1 ON PROVEEDOR (CEDULA ASC) 
)
 ENABLE;

ALTER TABLE SERV_PROVEEDOR
ADD CONSTRAINT SERV_PROVEEDOR_UK1 UNIQUE 
(
  CODIGO 
)
ENABLE;

ALTER TABLE CLIENTE_EMAIL
ADD CONSTRAINT CLIENTE_EMAIL_CLIENTE_FK1 FOREIGN KEY
(
  ID_CLIENTE 
)
REFERENCES CLIENTE
(
  ID_CLIENTE 
)
ENABLE;

ALTER TABLE CLIENTE_TELEFONO
ADD CONSTRAINT FK_CLNT_TEL_CLIENT_ID_CLIENTE FOREIGN KEY
(
  ID_CLIENTE 
)
REFERENCES CLIENTE
(
  ID_CLIENTE 
)
ENABLE;

ALTER TABLE CONTRATO
ADD CONSTRAINT FK_CONT_CLNT_ID_CLIENTE FOREIGN KEY
(
  ID_CLIENTE 
)
REFERENCES CLIENTE
(
  ID_CLIENTE 
)
ENABLE;

ALTER TABLE CONTRATO
ADD CONSTRAINT FK_CONT_PRY_ID_PROYECTO FOREIGN KEY
(
  ID_PROYECTO 
)
REFERENCES PROYECTO
(
  ID_PROYECTO 
)
ENABLE;

ALTER TABLE CUENTAS_POR_COBRAR
ADD CONSTRAINT FK_CNT_CONT_ID_CONTRATO FOREIGN KEY
(
  ID_CONTRATO 
)
REFERENCES CONTRATO
(
  ID_CONTRATO 
)
ENABLE;

ALTER TABLE EMPLEADO_PROYECTO
ADD CONSTRAINT FK_EMP_PRY_ID_EMPLEADO FOREIGN KEY
(
  ID_EMPLEADO 
)
REFERENCES EMPLEADO
(
  ID_EMPLEADO 
)
ENABLE;

ALTER TABLE EMPLEADO_PROYECTO
ADD CONSTRAINT FK_EMP_PRY_ID_PROYECTO FOREIGN KEY
(
  ID_PROYECTO 
)
REFERENCES PROYECTO
(
  ID_PROYECTO 
)
ENABLE;

ALTER TABLE FACTURA
ADD CONSTRAINT FK_FACT_PROV_ID_PROVEEDOR FOREIGN KEY
(
  ID_PROVEEDOR 
)
REFERENCES PROVEEDOR
(
  ID_PROVEEDOR 
)
ENABLE;

ALTER TABLE FACTURA
ADD CONSTRAINT FK_FACT_PRY_ID_PROYECTO FOREIGN KEY
(
  ID_PROYECTO 
)
REFERENCES PROYECTO
(
  ID_PROYECTO 
)
ENABLE;

ALTER TABLE HORAS_TRABAJADAS
ADD CONSTRAINT FK_H_TRAB_EMP_ID_EMPLEADO FOREIGN KEY
(
  ID_EMPLEADO 
)
REFERENCES EMPLEADO
(
  ID_EMPLEADO 
)
ENABLE;

ALTER TABLE LINEA_FACTURA
ADD CONSTRAINT LINEA_FACTURA_FACTURA_FK FOREIGN KEY
(
  ID_FACTURA 
)
REFERENCES FACTURA
(
  ID_FACTURA 
)
ENABLE;

ALTER TABLE LOGIN
ADD CONSTRAINT FK_LOGIN_EMPLEADO FOREIGN KEY
(
  ID_EMPLEADO 
)
REFERENCES EMPLEADO
(
  ID_EMPLEADO 
)
ENABLE;

ALTER TABLE L_MAT_PROVEEDOR
ADD CONSTRAINT FK_L_MAT_PROVEEDOR FOREIGN KEY
(
  CODIGO 
)
REFERENCES MAT_PROVEEDOR
(
  CODIGO 
)
ENABLE;

ALTER TABLE L_MAT_PROVEEDOR
ADD CONSTRAINT FK_L_MAT_PROV_FACT_ID_FACTURA FOREIGN KEY
(
  ID_FACTURA 
)
REFERENCES LINEA_FACTURA
(
  ID_FACTURA 
)
ENABLE;

ALTER TABLE L_SER_PROVEEDOR
ADD CONSTRAINT FK_L_SER_PROVEEDOR FOREIGN KEY
(
  CODIGO 
)
REFERENCES SERV_PROVEEDOR
(
  CODIGO 
)
ENABLE;

ALTER TABLE L_SER_PROVEEDOR
ADD CONSTRAINT FK_L_SER_PROV_FACT_ID_FACTURA FOREIGN KEY
(
  ID_FACTURA 
)
REFERENCES LINEA_FACTURA
(
  ID_FACTURA 
)
ENABLE;

ALTER TABLE MAT_PROVEEDOR
ADD CONSTRAINT FK_MAT_PROV_MAT_CODIGO FOREIGN KEY
(
  CODIGO 
)
REFERENCES MATERIAL
(
  CODIGO 
)
ENABLE;

ALTER TABLE MAT_PROVEEDOR
ADD CONSTRAINT FK_MAT_PROV_PROV_ID_PROVEEDOR FOREIGN KEY
(
  ID_PROVEEDOR 
)
REFERENCES PROVEEDOR
(
  ID_PROVEEDOR 
)
ENABLE;

ALTER TABLE PROVEEDOR_EMAIL
ADD CONSTRAINT FK_EMAIL_PROV_ID_PROVEEDOR FOREIGN KEY
(
  ID_PROVEEDOR 
)
REFERENCES PROVEEDOR
(
  ID_PROVEEDOR 
)
ENABLE;

ALTER TABLE PROVEEDOR_TELEFONO
ADD CONSTRAINT FK_TEL_PROV_ID_PROVEEDOR FOREIGN KEY
(
  ID_PROVEEDOR 
)
REFERENCES PROVEEDOR
(
  ID_PROVEEDOR 
)
ENABLE;

ALTER TABLE PROYECTO_SUPERVISOR
ADD CONSTRAINT PROYECTO_SUPERVISOR_FK1 FOREIGN KEY
(
  ID_EMPLEADO 
)
REFERENCES EMPLEADO
(
  ID_EMPLEADO 
)
ENABLE;

ALTER TABLE PROYECTO_SUPERVISOR
ADD CONSTRAINT PROYECTO_SUPERVISOR_FK2 FOREIGN KEY
(
  ID_PROYECTO 
)
REFERENCES PROYECTO
(
  ID_PROYECTO 
)
ENABLE;

ALTER TABLE SERV_PROVEEDOR
ADD CONSTRAINT FK_PROV_SRVC_CODIGO FOREIGN KEY
(
  CODIGO 
)
REFERENCES SERVICIO
(
  CODIGO 
)
ENABLE;

ALTER TABLE SERV_PROVEEDOR
ADD CONSTRAINT FK_PROV_SRVC_ID_PROVEEDOR FOREIGN KEY
(
  ID_PROVEEDOR 
)
REFERENCES PROVEEDOR
(
  ID_PROVEEDOR 
)
ENABLE;

ALTER TABLE CUENTAS_POR_COBRAR
ADD CONSTRAINT CK_CNT_ESTADO CHECK 
(ESTADO = 'P' OR ESTADO = 'C')
ENABLE;

ALTER TABLE EMPLEADO
ADD CONSTRAINT CK_EMP_FCH_REGISTRO CHECK 
(FECHA_REGISTRO = GETDATE())
ENABLE;

ALTER TABLE EMPLEADO
ADD CONSTRAINT CK_EMP_FCH_ULT_MOD CHECK 
(FECHA_ULT_MOD = GETDATE())
ENABLE;

ALTER TABLE FACTURA
ADD CONSTRAINT CK_FACTURA_FCH CHECK 
(FECHA_FACTURA = GETDATE())
ENABLE;

ALTER TABLE FACTURA
ADD CONSTRAINT CK_FACTURA_ULT_MOD CHECK 
(FECHA_ULT_MOD = GETDATE())
ENABLE;

ALTER TABLE HORAS_TRABAJADAS
ADD CONSTRAINT CK_H_TRAB_ESTADO CHECK 
(ESTADO = 'P' OR ESTADO = 'C')
ENABLE;

ALTER TABLE LINEA_FACTURA
ADD CONSTRAINT CK_L_F_FCH_REGISTRO CHECK 
(FECHA_REGISTRO = GETDATE())
ENABLE;

ALTER TABLE LINEA_FACTURA
ADD CONSTRAINT CK_L_F_FCH_ULT_MOD CHECK 
(FECHA_ULT_MOD = GETDATE())
ENABLE;

ALTER TABLE PROVEEDOR
ADD CONSTRAINT CK_PROV_FCH_REGISTRO CHECK 
(FECHA_REGISTRO = getdate())
ENABLE;

ALTER TABLE PROVEEDOR
ADD CONSTRAINT CK_PROV_FCH_U_MOD CHECK 
(FECHA_ULT_MOD = getdate())
ENABLE;

ALTER TABLE PROVEEDOR_EMAIL
ADD CONSTRAINT CK_EMAIL_PROV_FCH_REGISTRO CHECK 
(FECHA_REGISTRO= GETDATE())
ENABLE;

ALTER TABLE PROVEEDOR_EMAIL
ADD CONSTRAINT CK_EMAIL_PROV_FCH_ULT_MOD CHECK 
(FECHA_ULT_MOD = GETDATE())
ENABLE;

ALTER TABLE SERVICIO
ADD CONSTRAINT CK_SRVC_FCH_REGISTRO CHECK 
(FECHA_REGISTRO = GETDATE())
ENABLE;

ALTER TABLE SERVICIO
ADD CONSTRAINT CK_SRVC_FCH_ULT_MOD CHECK 
(FECHA_ULT_MOD = GETDATE())
ENABLE;

ALTER TABLE SERV_PROVEEDOR
ADD CONSTRAINT CK_PROV_SRVC_FCH_REGISTRO CHECK 
(FECHA_REGISTRO = GETDATE())
ENABLE;

ALTER TABLE SERV_PROVEEDOR
ADD CONSTRAINT CK_PROV_SRVC_FCH_ULT_MOD CHECK 
(FECHA_ULT_MOD = GETDATE())
ENABLE;

COMMENT ON TABLE CLIENTE IS 'Relación de la entidad cliente, que son las personas que adquieren proyectos, se relacionan con los proyectos a través de contratos.';

COMMENT ON TABLE EMPLEADO IS 'Planilla total de la compañia, se encuentran todos los empleado, los cuales trabajan en mínimo un proyecto.';

COMMENT ON TABLE EMPLEADO_PROYECTO IS 'Tabla para determinar qué empleado trabaja en qué proyecto.';

COMMENT ON TABLE FACTURA IS 'Relación entre un proveedor, productos adquiridos y un supervisor que adquiere el producto.';

COMMENT ON TABLE HORAS_TRABAJADAS IS 'Cantidad de horas trabajadas por un empleado, también guarda el salario de cada empleado por hora para manejar el pago de salarios.';

COMMENT ON TABLE LINEA_FACTURA IS 'Detalle de las facturas.';

COMMENT ON TABLE LOGIN IS 'Debido a que no todos los empleados usan el sistema, esta tabla funciona para asignar usuarios de login y contraseñas a los empleados que sí usan el sistema.';

COMMENT ON TABLE MATERIAL IS 'Catálogo de materiales que han sido adquiridos.';

COMMENT ON TABLE MAT_PROVEEDOR IS 'Relación entre materiales y proveedores.';

COMMENT ON TABLE PROVEEDOR IS 'Catálogo total de proveedores, los caules pueden proveer ya sea un producto o un servicio.';

COMMENT ON TABLE PROVEEDOR_TELEFONO IS 'Tabla con los números de teléfono de cada proveedor.';

COMMENT ON TABLE PROYECTO IS 'Tabla de proyectos, donde se maneja todo lo relacionado, se liga con los clientes a través de un contrato.';

COMMENT ON TABLE PROYECTO_SUPERVISOR IS 'Tabla que registra qué supervisor supervisa cada proyecto.';

COMMENT ON TABLE SERV_PROVEEDOR IS 'Relación entre servicio y el proveedor que lo da.';

COMMENT ON COLUMN CLIENTE.ID_CLIENTE IS 'Identificador del cliente.';

COMMENT ON COLUMN CLIENTE.CEDULA IS 'Número  de cédula del cliente.';

COMMENT ON COLUMN CLIENTE.NOMBRE IS 'Nombre del cliente.';

COMMENT ON COLUMN CLIENTE.DIRECCION IS 'Dirección donde vive el cliente.';

COMMENT ON COLUMN CLIENTE.ID_REGISTRO IS 'Usuario que registra al cliente.';

COMMENT ON COLUMN CLIENTE.FECHA_REGISTRO IS 'Fecha en que se registra el cliente.';

COMMENT ON COLUMN CLIENTE.ID_ULT_MOD IS 'Usuario que realizó la última modificación al cliente.';

COMMENT ON COLUMN CLIENTE.FECHA_ULT_MOD IS 'Fecha en la que se realizó la última modificación a la fila.';

COMMENT ON COLUMN CLIENTE_EMAIL.CORREO IS 'Correo electrónico del cliente.';

COMMENT ON COLUMN CLIENTE_EMAIL.ID_CLIENTE IS 'Cliente que al que pertenceel correo.';

COMMENT ON COLUMN CLIENTE_EMAIL.ID_REGISTRO IS 'Persona que registró el correo.';

COMMENT ON COLUMN CLIENTE_EMAIL.FECHA_REGISTRO IS 'Fehca en que se registró el correo.';

COMMENT ON COLUMN CLIENTE_EMAIL.ID_ULT_MOD IS 'Id de la persona que hizo la última modificación al correo';

COMMENT ON COLUMN CLIENTE_EMAIL.FECHA_ULT_MOD IS 'Fecha de la última modificación a la tabla';

COMMENT ON COLUMN CLIENTE_TELEFONO.TELEFONO IS 'Teléfono del cliente.';

COMMENT ON COLUMN CLIENTE_TELEFONO.ID_CLIENTE IS 'Cliente al que pertenece el teléfono.';

COMMENT ON COLUMN CLIENTE_TELEFONO.ID_REGISTRO IS 'Usuario que registró el teléfono.';

COMMENT ON COLUMN CLIENTE_TELEFONO.FECHA_REGISTRO IS 'Fecha en la que se registró el teléfono.';

COMMENT ON COLUMN CLIENTE_TELEFONO.ID_ULT_MOD IS 'Usuario que realizó la última modificación al teléfono.';

COMMENT ON COLUMN CLIENTE_TELEFONO.FECHA_ULT_MOD IS 'Fehca en que se realizó la última modificación al teléfono.';

COMMENT ON COLUMN CUENTAS_POR_COBRAR.ID_CONTRATO IS 'Identificador de la cuenta';

COMMENT ON COLUMN CUENTAS_POR_COBRAR.ESTADO IS 'Estado de la cuenta, se refiere si fue cancelada o sigue pendiente';

COMMENT ON COLUMN CUENTAS_POR_COBRAR.MONTO_TOTAL IS 'Monto total que vale la cuenta';

COMMENT ON COLUMN CUENTAS_POR_COBRAR.MONTO_PAGADO IS 'Monto que se ha pagado hasta el momento, se utiliza para no perder el valor inicial de la cuenta.';

COMMENT ON COLUMN CUENTAS_POR_COBRAR.ID_REGISTRO IS 'Usuario que registró la cuenta.';

COMMENT ON COLUMN CUENTAS_POR_COBRAR.FECHA_REGISTRO IS 'Fecha en que se reginstró una cuenta.';

COMMENT ON COLUMN CUENTAS_POR_COBRAR.ID_ULT_MOD IS 'Usuario que modificó por última vez la cuenta.';

COMMENT ON COLUMN CUENTAS_POR_COBRAR.FECHA_ULT_MOD IS 'Fecha de la última modificación del contrato.';

COMMENT ON COLUMN EMPLEADO.ID_EMPLEADO IS 'Identificador del empleado dentro de la empresa.';

COMMENT ON COLUMN EMPLEADO.CEDULA IS 'Cédula del empleado.';

COMMENT ON COLUMN EMPLEADO.FECHA_INGRESO IS 'Fecha de ingreso a la empresa';

COMMENT ON COLUMN EMPLEADO.NOMBRE IS 'Nombre del empleado.';

COMMENT ON COLUMN EMPLEADO.TELEFONO IS 'Telefono del empleado.';

COMMENT ON COLUMN EMPLEADO.DIRECCION IS 'Dirección de la vivienda del empleado.';

COMMENT ON COLUMN EMPLEADO.ID_REGISTRO IS 'Usuario que registró al empleado';

COMMENT ON COLUMN EMPLEADO.FECHA_REGISTRO IS 'Fecha en que se registra el empleado';

COMMENT ON COLUMN EMPLEADO.ID_ULT_MOD IS 'Usuario que realizó la última modificación al empleado.';

COMMENT ON COLUMN EMPLEADO.FECHA_ULT_MOD IS 'Fecha en la que se realiza la última modificación al empleado.';

COMMENT ON COLUMN EMPLEADO_PROYECTO.ID_PROYECTO IS 'Proyecto en el que trabaja el empleado.';

COMMENT ON COLUMN EMPLEADO_PROYECTO.ID_EMPLEADO IS 'Empleado que trabaja en el proyecto.';

COMMENT ON COLUMN EMPLEADO_PROYECTO.ID_ULT_MOD IS 'Usuario que realizó la última modificación en la fila.';

COMMENT ON COLUMN EMPLEADO_PROYECTO.FECHA_ULT_MOD IS 'Fecha en la que se realizó la última modificación a la fila.';

COMMENT ON COLUMN FACTURA.ID_FACTURA IS 'Identificador de la factura.';

COMMENT ON COLUMN FACTURA.ID_PROVEEDOR IS 'Proveedor que vendió el producto.';

COMMENT ON COLUMN FACTURA.ID_PROYECTO IS 'Proyecto para el cuál se adquirió el producto.';

COMMENT ON COLUMN FACTURA.MONTO_TOTAL IS 'Monto inicial por el que se adquieren los productos.';

COMMENT ON COLUMN FACTURA.SALDO_PENDIENTE IS 'Saldo que queda aún no se paga de la factura';

COMMENT ON COLUMN FACTURA.FECHA_FACTURA IS 'Fecha en la que se realiza la factura.';

COMMENT ON COLUMN FACTURA.FECHA_VENCIMIENTO IS 'Fecha de vencimiento de la factura.';

COMMENT ON COLUMN FACTURA.QUINCENA IS 'Quincena en la que se hace la compra.';

COMMENT ON COLUMN FACTURA.ID_REGISTRO IS 'Usuario que registra la factura.';

COMMENT ON COLUMN FACTURA.FECHA_REGISTRO IS 'Fecha en que se registra la factura';

COMMENT ON COLUMN FACTURA.ID_ULT_MOD IS 'Usuario que hizo la última modificación a la factura.';

COMMENT ON COLUMN FACTURA.FECHA_ULT_MOD IS 'Fecha de la última modificación a la factura';

COMMENT ON COLUMN HORAS_TRABAJADAS.ID_PROYECTO IS 'Proyecto en el que se trabajó la cantidad de horas dichas.';

COMMENT ON COLUMN HORAS_TRABAJADAS.CANTIDAD_DE_HORAS IS 'Cantidad de horas que se trabajó en el proyecto.';

COMMENT ON COLUMN HORAS_TRABAJADAS.ESTADO IS 'Estado del pago del salario, si está pendiente o cancelado.';

COMMENT ON COLUMN HORAS_TRABAJADAS.ID_EMPLEADO IS 'Empleado que registró la cantidad de horas';

COMMENT ON COLUMN HORAS_TRABAJADAS.SALARIO_HORA IS 'Salario por hora del empleado.';

COMMENT ON COLUMN HORAS_TRABAJADAS.FECHA_REGISTRO IS 'Fecha en la que se registra la cantidad de horas.';

COMMENT ON COLUMN HORAS_TRABAJADAS.ID_ULT_MOD IS 'Persona que realizó la última modificación  a la cantidad de horas';

COMMENT ON COLUMN HORAS_TRABAJADAS.FECHA_ULT_MOD IS 'Fecha en que se realiza la última modificación a la cantidad de horas.';

COMMENT ON COLUMN LINEA_FACTURA.ID_FACTURA IS 'Factura de la cuál se da el detalle.';

COMMENT ON COLUMN LINEA_FACTURA.ID_LINEA IS 'Identificador de línea.';

COMMENT ON COLUMN LINEA_FACTURA.ID_REGISTRO IS 'Persona que registra el detalle.';

COMMENT ON COLUMN LINEA_FACTURA.FECHA_REGISTRO IS 'Fecha en que se registra el detalle de la factura.';

COMMENT ON COLUMN LINEA_FACTURA.ID_ULT_MOD IS 'Persona que realizó la última modificación.';

COMMENT ON COLUMN LINEA_FACTURA.FECHA_ULT_MOD IS 'Última modificación hecha al detalle de la factura.';

COMMENT ON COLUMN LOGIN.LOGIN IS 'Usuario con el que accede un usuario al sistema.';

COMMENT ON COLUMN LOGIN.ID_EMPLEADO IS 'Empleado al que pertenece el usuario y la contraseña.';

COMMENT ON COLUMN LOGIN.PASSWORD IS 'Contraseña del usuario';

COMMENT ON COLUMN LOGIN.ID_REGISTRO IS 'Persona que registró al usuario.';

COMMENT ON COLUMN LOGIN.FECHA_REGISTRO IS 'Fecha en que se registra el usuario.';

COMMENT ON COLUMN LOGIN.ID_ULT_MOD IS 'Último usuario que realizó la última modifciación al usuario.';

COMMENT ON COLUMN LOGIN.FECHA_ULT_MOD IS 'Fecha en la que se realiza la última modificación al usuario.';

COMMENT ON COLUMN L_MAT_PROVEEDOR.CODIGO IS 'Código del material detro del catálogo de la compañía.';

COMMENT ON COLUMN L_MAT_PROVEEDOR.ID_FACTURA IS 'Identificador de la factura.';

COMMENT ON COLUMN L_MAT_PROVEEDOR.ID_LINEA IS 'Identificador de la línea.';

COMMENT ON COLUMN L_MAT_PROVEEDOR.CANTIDAD IS 'Cantidad de material recibido.';

COMMENT ON COLUMN L_MAT_PROVEEDOR.COSTO_UNITARIO IS 'Costo unitario.';

COMMENT ON COLUMN L_MAT_PROVEEDOR.UNIDAD_MEDIDA IS 'Unidad de medida del servicio.';

COMMENT ON COLUMN L_MAT_PROVEEDOR.ID_REGISTRO IS 'Persona que registra el detalle.';

COMMENT ON COLUMN L_MAT_PROVEEDOR.FECHA_REGISTRO IS 'Fecha en la que se inscribe el detalle.';

COMMENT ON COLUMN L_MAT_PROVEEDOR.ID_ULT_MOD IS 'Persona que realiza la última modificación.';

COMMENT ON COLUMN L_MAT_PROVEEDOR.FECHA_ULT_MOD IS 'Fecha en la que se realiza la última modificación.';

COMMENT ON COLUMN L_SER_PROVEEDOR.CODIGO IS 'Código del servicio dentro del catálogo de la compañía.';

COMMENT ON COLUMN L_SER_PROVEEDOR.ID_FACTURA IS 'Número de factura al que pertenece.';

COMMENT ON COLUMN L_SER_PROVEEDOR.ID_LINEA IS 'Número de línea al que pertenece.';

COMMENT ON COLUMN L_SER_PROVEEDOR.ID_PROVEEDOR IS 'Proveedor que suministra el servicio.';

COMMENT ON COLUMN L_SER_PROVEEDOR.COSTO_UNITARIO IS 'Costo de cada unidad de servicio contratado.';

COMMENT ON COLUMN L_SER_PROVEEDOR.CANTIDAD IS 'Cantidad de servicio recibido';

COMMENT ON COLUMN L_SER_PROVEEDOR.UNIDAD_MEDIDA IS 'Unidad de medida del servicio recibido.';

COMMENT ON COLUMN L_SER_PROVEEDOR.ID_REGISTRO IS 'Persona que registra el detalle.';

COMMENT ON COLUMN L_SER_PROVEEDOR.FECHA_REGISTRO IS 'Fecha en que se registra el detalle.';

COMMENT ON COLUMN L_SER_PROVEEDOR.ID_ULT_MOD IS 'Persona que realizó la última modificación.';

COMMENT ON COLUMN L_SER_PROVEEDOR.FECHA_ULT_MOD IS 'Fecha de la última modificación.';

COMMENT ON COLUMN MATERIAL.CODIGO IS 'Código mediante el cuál se identifica el material.';

COMMENT ON COLUMN MATERIAL.DESCRIPCION IS 'Descripción del material.';

COMMENT ON COLUMN MATERIAL.U_COSTO_COLONES IS 'Último costo en colones del material.';

COMMENT ON COLUMN MATERIAL.ID_REGISTRO IS 'Persona que registra el material.';

COMMENT ON COLUMN MATERIAL.FECHA_REGISTRO IS 'Fecha en que se registra el material.';

COMMENT ON COLUMN MATERIAL.ID_ULT_MOD IS 'Persona que realiza la última modificación.';

COMMENT ON COLUMN MATERIAL.FECHA_ULT_MOD IS 'Fecha en la que se realiza la última modificación.';

COMMENT ON COLUMN MAT_PROVEEDOR.ID_PROVEEDOR IS 'Proveedor que suministra el material.';

COMMENT ON COLUMN MAT_PROVEEDOR.CODIGO IS 'Código del material detro del catálogo de la compañía.';

COMMENT ON COLUMN MAT_PROVEEDOR.CODIGO_MAT_PROV IS 'Código del material dentro del catálogo del proveedor.';

COMMENT ON COLUMN MAT_PROVEEDOR.ID_REGISTRO IS 'Persona que registra la relación.';

COMMENT ON COLUMN MAT_PROVEEDOR.FECHA_REGISTRO IS 'Fecha en que se registra la relación.';

COMMENT ON COLUMN MAT_PROVEEDOR.ID_ULT_MOD IS 'Persona que realiza la última modificación a la fila.';

COMMENT ON COLUMN MAT_PROVEEDOR.FECHA_ULT_MOD IS 'Fecha de la última modificación a la fila';

COMMENT ON COLUMN PROVEEDOR.ID_PROVEEDOR IS 'Identificador del proveedor.';

COMMENT ON COLUMN PROVEEDOR.NBR_PROVEEDOR IS 'Nombre del proveedor';

COMMENT ON COLUMN PROVEEDOR.DIRECCION IS 'Dirección de residencia.';

COMMENT ON COLUMN PROVEEDOR.CEDULA IS 'Cédula de identidad del proveedor.';

COMMENT ON COLUMN PROVEEDOR.ID_REGISTRO IS 'Usuario que registró al proveedor.';

COMMENT ON COLUMN PROVEEDOR.FECHA_REGISTRO IS 'Fecha en que se registra al proveedor';

COMMENT ON COLUMN PROVEEDOR.ID_U_MOD IS 'Último usuario que realiza una modificación.';

COMMENT ON COLUMN PROVEEDOR.FECHA_ULT_MOD IS 'Fecha en la que se realiza la última modificación al proveedor';

COMMENT ON COLUMN PROVEEDOR_EMAIL.CORREO IS 'Correo electrónico del proveedor.';

COMMENT ON COLUMN PROVEEDOR_EMAIL.ID_PROVEEDOR IS 'Proveedor al que pertenece el correo electrónico.';

COMMENT ON COLUMN PROVEEDOR_EMAIL.ID_REGISTRO IS 'Persona que registra el correo.';

COMMENT ON COLUMN PROVEEDOR_EMAIL.FECHA_REGISTRO IS 'Fecha en que se registra la última modificación al correo.';

COMMENT ON COLUMN PROVEEDOR_EMAIL.ID_ULT_MOD IS 'Persona que realiza la última modificación al correo.';

COMMENT ON COLUMN PROVEEDOR_EMAIL.FECHA_ULT_MOD IS 'Fecha de la última modificación del correo electrónico.';

COMMENT ON COLUMN PROVEEDOR_TELEFONO.TELEFONO IS 'Número telefónico de cada proveedor.';

COMMENT ON COLUMN PROVEEDOR_TELEFONO.ID_PROVEEDOR IS 'Proveedor al que pertenece.';

COMMENT ON COLUMN PROVEEDOR_TELEFONO.ID_REGISTRO IS 'Persona que registró el número.';

COMMENT ON COLUMN PROVEEDOR_TELEFONO.FECHA_REGISTRO IS 'Fecha en que se registra el teléfono.';

COMMENT ON COLUMN PROVEEDOR_TELEFONO.ID_ULT_MOD IS 'Persona que realizó la última modificación al teléfono.';

COMMENT ON COLUMN PROVEEDOR_TELEFONO.FECHA_ULT_MOD IS 'Fecha en que se realizó la última modificación al teléfono.';

COMMENT ON COLUMN PROYECTO.ID_PROYECTO IS 'Identificador de cada proyecto.';

COMMENT ON COLUMN PROYECTO.DESCRIPCION IS 'Descripción sobre qué consiste el proyecto';

COMMENT ON COLUMN PROYECTO.ID_REGISTRO IS 'Persona que registró el proyecto.';

COMMENT ON COLUMN PROYECTO.FECHA_REGISTRO IS 'Fecha en que se registró el proyecto';

COMMENT ON COLUMN PROYECTO.ID_ULT_MOD IS 'Fecha en que se realizó la última modificación a la fila.';

COMMENT ON COLUMN PROYECTO.FECHA_ULT_MOD IS 'Fecha en que se realizó la última modificación.';

COMMENT ON COLUMN PROYECTO_SUPERVISOR.FECHA_INICIO IS 'Fecha en que el empleado inicio a supervisar el proyecto.';

COMMENT ON COLUMN PROYECTO_SUPERVISOR.ID_EMPLEADO IS 'Empleado que supervisa el proyecto dado.';

COMMENT ON COLUMN PROYECTO_SUPERVISOR.ID_PROYECTO IS 'Proyecto que es supervisado por el empleado';

COMMENT ON COLUMN PROYECTO_SUPERVISOR.FECHA_FINAL IS 'Fecha en la que el empleadtermina de supervisar el proyecto';

COMMENT ON COLUMN PROYECTO_SUPERVISOR.ID_REGISTRO IS 'Empleado que registró al supervisor.';

COMMENT ON COLUMN PROYECTO_SUPERVISOR.FECHA_REGISTRO IS 'Fecha en la que se registró el supervisor.';

COMMENT ON COLUMN PROYECTO_SUPERVISOR.FECHA_ULT_MOD IS 'Fecha en la que se hizo la última modificación en la fila.';

COMMENT ON COLUMN SERVICIO.CODIGO IS 'Código con el cual se identifica al servicio.';

COMMENT ON COLUMN SERVICIO.DESCRIPCION IS 'Descripción del servicio.';

COMMENT ON COLUMN SERVICIO.ID_REGISTRO IS 'Persona que registra el servicio.';

COMMENT ON COLUMN SERVICIO.FECHA_REGISTRO IS 'Fecha en que se registra el servicio.';

COMMENT ON COLUMN SERVICIO.ID_ULT_MOD IS 'Persona que realiza la última modificación.';

COMMENT ON COLUMN SERVICIO.FECHA_ULT_MOD IS 'Fecha en la que se realiza la última modificación a un servicio.';

COMMENT ON COLUMN SERV_PROVEEDOR.ID_PROVEEDOR IS 'Proveedor que suminstra el servicio.';

COMMENT ON COLUMN SERV_PROVEEDOR.CODIGO IS 'Código del servicio dentro del catálogo de la compañía.';

COMMENT ON COLUMN SERV_PROVEEDOR.CODIGO_SERV_PROV IS 'Código del servicio dentro del catálogo  del proveedor.';

COMMENT ON COLUMN SERV_PROVEEDOR.ID_REGISTRO IS 'Persona que registra la relación.';

COMMENT ON COLUMN SERV_PROVEEDOR.FECHA_REGISTRO IS 'Fecha en que se registra la relación.';

COMMENT ON COLUMN SERV_PROVEEDOR.ID_ULT_MOD IS 'Perrsona que realiza la última modificación a la relación.';

COMMENT ON COLUMN SERV_PROVEEDOR.FECHA_ULT_MOD IS 'Fecha de la última modificación a la relación.';
