SET SQLBLANKLINES ON
CREATE TABLE CLIENTE 
(
  ID_CLIENTE VARCHAR(6) NOT NULL 
, CEDULA NUMERIC(9) NOT NULL 
, NOMBRE VARCHAR(30) NOT NULL 
, DIRECCION VARCHAR(30) DEFAULT 'Sin direccion' NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE NOT NULL 
, CONSTRAINT PK_CLIENTE PRIMARY KEY 
  (
    ID_CLIENTE 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CLIENTE_PK ON CLIENTE (ID_CLIENTE ASC) 
  )
  ENABLE 
);

CREATE TABLE EMPLEADO 
(
  ID_EMPLEADO VARCHAR(6) NOT NULL 
, CEDULA NUMERIC(9) NOT NULL 
, FECHA_INGRESO DATE NOT NULL 
, NOMBRE VARCHAR(20) NOT NULL 
, TELEFONO NUMERIC(8) NOT NULL 
, DIRECCION VARCHAR(50) NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE NOT NULL 
, CONSTRAINT PK_EMPLEADO PRIMARY KEY 
  (
    ID_EMPLEADO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX EMPLEADO_PK ON EMPLEADO (ID_EMPLEADO ASC) 
  )
  ENABLE 
);

CREATE TABLE MATERIAL 
(
  CODIGO VARCHAR(6) NOT NULL 
, DESCRIPCION VARCHAR(40) DEFAULT 'Sin descripcion' NOT NULL 
, U_COSTO_COLONES NUMERIC(9) NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE DEFAULT GETDATE() NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE DEFAULT GETDATE() NOT NULL 
, CONSTRAINT MATERIAL_PK PRIMARY KEY 
  (
    CODIGO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX MATERIAL_AD_PK ON MATERIAL (CODIGO ASC) 
  )
  ENABLE 
);

CREATE TABLE PROVEEDOR 
(
  ID_PROVEEDOR VARCHAR(6) NOT NULL 
, NBR_PROVEEDOR VARCHAR(30) NOT NULL 
, DIRECCION VARCHAR(50) DEFAULT 'Sin direccion' NOT NULL 
, CEDULA NUMERIC(9) NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE NOT NULL 
, ID_U_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE DEFAULT GETDATE() NOT NULL 
, CONSTRAINT PK_PROVEEDOR PRIMARY KEY 
  (
    ID_PROVEEDOR 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PROVEEDOR_PK ON PROVEEDOR (ID_PROVEEDOR ASC) 
  )
  ENABLE 
);

CREATE TABLE PROYECTO 
(
  ID_PROYECTO VARCHAR(8) NOT NULL 
, DESCRIPCION VARCHAR(40) DEFAULT 'Sin descripcion' NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE NOT NULL 
, CONSTRAINT PK_PROYECTO PRIMARY KEY 
  (
    ID_PROYECTO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PROYECTO_PK ON PROYECTO (ID_PROYECTO ASC) 
  )
  ENABLE 
);

CREATE TABLE SERVICIO 
(
  CODIGO VARCHAR(6) NOT NULL 
, DESCRIPCION VARCHAR2(40) DEFAULT 'Sin Descripcion' NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE DEFAULT getdate() NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE DEFAULT getdate() NOT NULL 
, CONSTRAINT PK_SERVICIO PRIMARY KEY 
  (
    CODIGO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SERVICIOS_AD_PK ON SERVICIO (CODIGO ASC) 
  )
  ENABLE 
);

CREATE TABLE CLIENTE_EMAIL 
(
  CORREO VARCHAR(30) NOT NULL 
, ID_CLIENTE VARCHAR(6) NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE NOT NULL 
, CONSTRAINT CLIENTE_EMAIL_PK PRIMARY KEY 
  (
    CORREO 
  )
  ENABLE 
);

CREATE TABLE CLIENTE_TELEFONO 
(
  TELEFONO NUMERIC(8) NOT NULL 
, ID_CLIENTE VARCHAR(6) NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE NOT NULL 
, CONSTRAINT PK_CLIENTE_TELEFONO PRIMARY KEY 
  (
    TELEFONO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CLIENTE_TELEFONO_PK ON CLIENTE_TELEFONO (TELEFONO ASC) 
  )
  ENABLE 
);

CREATE TABLE HORAS_TRABAJADAS 
(
  ID_EMPLEADO VARCHAR(6) NOT NULL 
, ID_PROYECTO VARCHAR(8) NOT NULL 
, CANTIDAD_DE_HORAS NUMERIC(6) DEFAULT 1 NOT NULL 
, QUINCENA DATE NOT NULL 
, ESTADO CHAR(1) DEFAULT 'P' NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE DEFAULT getdate() NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE DEFAULT getdate() NOT NULL 
);

CREATE TABLE MAT_PROVEEDOR 
(
  ID_PROVEEDOR VARCHAR(6) NOT NULL 
, CODIGO VARCHAR(6) NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE NOT NULL 
, CONSTRAINT PK_MAT_PROVEEDOR PRIMARY KEY 
  (
    CODIGO 
  , ID_PROVEEDOR 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX MAT_PROOVEDOR_PK ON MAT_PROVEEDOR (CODIGO ASC, ID_PROVEEDOR ASC) 
  )
  ENABLE 
);

CREATE TABLE PROVEEDOR_EMAIL 
(
  CORREO VARCHAR(50) NOT NULL 
, ID_PROVEEDOR VARCHAR(6) NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE NOT NULL 
, CONSTRAINT PK_EMAIL PRIMARY KEY 
  (
    CORREO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX EMAIL_PK ON PROVEEDOR_EMAIL (CORREO ASC) 
  )
  ENABLE 
);

CREATE TABLE PROVEEDOR_TELEFONO 
(
  TELEFONO NUMERIC(8) NOT NULL 
, ID_PROVEEDOR VARCHAR(6) NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE NOT NULL 
, CONSTRAINT PK_TELEFONO_PROVEEDOR PRIMARY KEY 
  (
    TELEFONO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX TELEFONO_PROVEEDOR_PK ON PROVEEDOR_TELEFONO (TELEFONO ASC) 
  )
  ENABLE 
);

CREATE TABLE CONTRATO 
(
  ID_CONTRATO VARCHAR(6) NOT NULL 
, ID_CLIENTE VARCHAR(6) NOT NULL 
, ID_PROYECTO VARCHAR(8) NOT NULL 
, PLAZO_MESES NUMERIC(6) NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE NOT NULL 
, CONSTRAINT PK_CONTRATO PRIMARY KEY 
  (
    ID_CONTRATO 
  )
  ENABLE 
);

CREATE TABLE EMPLEADO_PROYECTO 
(
  ID_PROYECTO VARCHAR(8) NOT NULL 
, ID_EMPLEADO VARCHAR(6) NOT NULL 
, SALARIO_HORA NUMERIC(8) NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE NOT NULL 
, CONSTRAINT PK_EMP_PRY PRIMARY KEY 
  (
    ID_EMPLEADO 
  , ID_PROYECTO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX EMPLEADOPROYECTO_PK ON EMPLEADO_PROYECTO (ID_EMPLEADO ASC, ID_PROYECTO ASC) 
  )
  ENABLE 
);

CREATE TABLE FACTURA 
(
  ID_FACTURA VARCHAR(6) NOT NULL 
, ID_PROVEEDOR VARCHAR(6) NOT NULL 
, ID_PROYECTO VARCHAR(8) NOT NULL 
, MONTO_TOTAL NUMERIC(10) NOT NULL 
, SALDO_PENDIENTE NUMERIC(10) NOT NULL 
, FECHA_FACTURA DATE NOT NULL 
, FECHA_VENCIMIENTO DATE NOT NULL 
, QUINCENA DATE NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE NOT NULL 
, CONSTRAINT PK_FACTURA PRIMARY KEY 
  (
    ID_FACTURA 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX FACTURA_PK ON FACTURA (ID_FACTURA ASC) 
  )
  ENABLE 
);

CREATE TABLE PROYECTO_SUPERVISOR 
(
  FECHA_INICIO DATE NOT NULL 
, ID_EMPLEADO VARCHAR(6) NOT NULL 
, ID_PROYECTO VARCHAR(8) NOT NULL 
, FECHA_FINAL DATE DEFAULT 2020-12-31 NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE DEFAULT GetDate() NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE DEFAULT GetDate() NOT NULL 
, CONSTRAINT PROYECTO_SUPERVISOR_PK PRIMARY KEY 
  (
    FECHA_INICIO 
  , ID_EMPLEADO 
  )
  ENABLE 
);

CREATE TABLE PROV_SERVICIO 
(
  CODIGO VARCHAR(6) NOT NULL 
, ID_PROVEEDOR VARCHAR(6) NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE NOT NULL 
, CONSTRAINT PK_PROV_SERVICIO PRIMARY KEY 
  (
    CODIGO 
  , ID_PROVEEDOR 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PROV_SERVICIO_PK ON PROV_SERVICIO (CODIGO ASC, ID_PROVEEDOR ASC) 
  )
  ENABLE 
);

CREATE TABLE CUENTAS_POR_COBRAR 
(
  ID_CONTRATO VARCHAR(6) NOT NULL 
, ESTADO CHAR(1) NOT NULL 
, MONTO_TOTAL NUMERIC(10) NOT NULL 
, MONTO_PAGADO NUMERIC(10) NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE NOT NULL 
, CONSTRAINT CUENTA_PK PRIMARY KEY 
  (
    ID_CONTRATO 
  )
  ENABLE 
);

CREATE TABLE GASTO 
(
  ID_PROYECTO VARCHAR(8) NOT NULL 
, ID_FACTURA VARCHAR(6) NOT NULL 
, ID_PROVEEDOR VARCHAR(6) NOT NULL 
, QUINCENA DATE NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE DEFAULT GETDATE() NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE DEFAULT GETDATE() NOT NULL 
, CONSTRAINT PK_GASTO PRIMARY KEY 
  (
    ID_PROYECTO 
  , ID_FACTURA 
  , ID_PROVEEDOR 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX GASTO_PK ON GASTO (ID_PROYECTO ASC, ID_FACTURA ASC, ID_PROVEEDOR ASC) 
  )
  ENABLE 
);

CREATE TABLE LINEA_FACTURA 
(
  ID_FACTURA VARCHAR(6) NOT NULL 
, ID_LINEA VARCHAR(6) NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE NOT NULL 
, CONSTRAINT PK_LINEA_FACTURA PRIMARY KEY 
  (
    ID_FACTURA 
  , ID_LINEA 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX LINEA_FACTURA_PK ON LINEA_FACTURA (ID_FACTURA ASC, ID_LINEA ASC) 
  )
  ENABLE 
);

CREATE TABLE L_MAT_PROVEEDOR 
(
  CODIGO VARCHAR(6) NOT NULL 
, ID_FACTURA VARCHAR(6) NOT NULL 
, ID_LINEA VARCHAR(6) NOT NULL 
, ID_PROVEEDOR VARCHAR(6) NOT NULL 
, CANTIDAD NUMERIC(6) NOT NULL 
, COSTO NUMERIC(10) NOT NULL 
, UNIDAD_MEDIDA CHAR(5) NOT NULL 
, COSTO_TOTAL NUMERIC(10) NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE NOT NULL 
, CONSTRAINT PK_L_MAT_PROVEEDOR PRIMARY KEY 
  (
    CODIGO 
  , ID_FACTURA 
  , ID_LINEA 
  , ID_PROVEEDOR 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX L_MAT_PROVEEDOR_PK ON L_MAT_PROVEEDOR (CODIGO ASC, ID_FACTURA ASC, ID_LINEA ASC, ID_PROVEEDOR ASC) 
  )
  ENABLE 
);

CREATE TABLE L_SER_PROVEEDOR 
(
  CODIGO VARCHAR(6) NOT NULL 
, ID_FACTURA VARCHAR(6) NOT NULL 
, ID_LINEA VARCHAR(6) NOT NULL 
, ID_PROVEEDOR VARCHAR(6) NOT NULL 
, COSTO NUMERIC(10) NOT NULL 
, CANTIDAD NUMERIC(6) NOT NULL 
, UNIDAD_MEDIDA CHAR(4) NOT NULL 
, COSTO_TOTAL NUMERIC(10) NOT NULL 
, ID_REGISTRO VARCHAR(6) NOT NULL 
, FECHA_REGISTRO DATE NOT NULL 
, ID_ULT_MOD VARCHAR(6) NOT NULL 
, FECHA_ULT_MOD DATE NOT NULL 
, CONSTRAINT PK_L_SER_PROVEEDOR PRIMARY KEY 
  (
    ID_PROVEEDOR 
  , ID_LINEA 
  , ID_FACTURA 
  , CODIGO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX L_SER_PROVEEDOR_PK ON L_SER_PROVEEDOR (ID_PROVEEDOR ASC, ID_LINEA ASC, ID_FACTURA ASC, CODIGO ASC) 
  )
  ENABLE 
);

ALTER TABLE CLIENTE
ADD CONSTRAINT UK_CLNT_CEDULA UNIQUE 
(
  CEDULA 
)
USING INDEX 
(
    CREATE UNIQUE INDEX CLIENTE_UK1 ON CLIENTE (CEDULA ASC) 
)
 ENABLE;

ALTER TABLE EMPLEADO
ADD CONSTRAINT UK_CEDULA UNIQUE 
(
  CEDULA 
)
USING INDEX 
(
    CREATE UNIQUE INDEX EMPLEADO_UK1 ON EMPLEADO (CEDULA ASC) 
)
 ENABLE;

ALTER TABLE LINEA_FACTURA
ADD CONSTRAINT LINEA_ID_FACTURA UNIQUE 
(
  ID_FACTURA 
)
USING INDEX 
(
    CREATE UNIQUE INDEX LINEA_FACTURA_UK1 ON LINEA_FACTURA (ID_FACTURA ASC) 
)
 ENABLE;

ALTER TABLE L_SER_PROVEEDOR
ADD CONSTRAINT L_SER_PROVEEDOR UNIQUE 
(
  ID_LINEA 
)
USING INDEX 
(
    CREATE UNIQUE INDEX L_SER_PROVEEDOR_UK1 ON L_SER_PROVEEDOR (ID_LINEA ASC) 
)
 ENABLE;

ALTER TABLE PROVEEDOR
ADD CONSTRAINT UK_PROV_CED UNIQUE 
(
  CEDULA 
)
USING INDEX 
(
    CREATE UNIQUE INDEX PROVEEDOR_UK1 ON PROVEEDOR (CEDULA ASC) 
)
 ENABLE;

ALTER TABLE CLIENTE_EMAIL
ADD CONSTRAINT CLIENTE_EMAIL_CLIENTE_FK1 FOREIGN KEY
(
  ID_CLIENTE 
)
REFERENCES CLIENTE
(
  ID_CLIENTE 
)
ENABLE;

ALTER TABLE CLIENTE_TELEFONO
ADD CONSTRAINT FK_CLNT_TEL_CLIENT_ID_CLIENTE FOREIGN KEY
(
  ID_CLIENTE 
)
REFERENCES CLIENTE
(
  ID_CLIENTE 
)
ENABLE;

ALTER TABLE CONTRATO
ADD CONSTRAINT FK_CONT_CLNT_ID_CLIENTE FOREIGN KEY
(
  ID_CLIENTE 
)
REFERENCES CLIENTE
(
  ID_CLIENTE 
)
ENABLE;

ALTER TABLE CONTRATO
ADD CONSTRAINT FK_CONT_PRY_ID_PROYECTO FOREIGN KEY
(
  ID_PROYECTO 
)
REFERENCES PROYECTO
(
  ID_PROYECTO 
)
ENABLE;

ALTER TABLE CUENTAS_POR_COBRAR
ADD CONSTRAINT FK_CNT_CONT_ID_CONTRATO FOREIGN KEY
(
  ID_CONTRATO 
)
REFERENCES CONTRATO
(
  ID_CONTRATO 
)
ENABLE;

ALTER TABLE EMPLEADO_PROYECTO
ADD CONSTRAINT FK_EMP_PRY_ID_EMPLEADO FOREIGN KEY
(
  ID_EMPLEADO 
)
REFERENCES EMPLEADO
(
  ID_EMPLEADO 
)
ENABLE;

ALTER TABLE EMPLEADO_PROYECTO
ADD CONSTRAINT FK_EMP_PRY_ID_PROYECTO FOREIGN KEY
(
  ID_PROYECTO 
)
REFERENCES PROYECTO
(
  ID_PROYECTO 
)
ENABLE;

ALTER TABLE FACTURA
ADD CONSTRAINT FK_FACT_PROV_ID_PROVEEDOR FOREIGN KEY
(
  ID_PROVEEDOR 
)
REFERENCES PROVEEDOR
(
  ID_PROVEEDOR 
)
ENABLE;

ALTER TABLE FACTURA
ADD CONSTRAINT FK_FACT_PRY_ID_PROYECTO FOREIGN KEY
(
  ID_PROYECTO 
)
REFERENCES PROYECTO
(
  ID_PROYECTO 
)
ENABLE;

ALTER TABLE GASTO
ADD CONSTRAINT FK_GST_FACT_ID_FACTURA FOREIGN KEY
(
  ID_FACTURA 
)
REFERENCES FACTURA
(
  ID_FACTURA 
)
ENABLE;

ALTER TABLE GASTO
ADD CONSTRAINT FK_GST_PROV_ID_PROVEEDOR FOREIGN KEY
(
  ID_PROVEEDOR 
)
REFERENCES PROVEEDOR
(
  ID_PROVEEDOR 
)
ENABLE;

ALTER TABLE GASTO
ADD CONSTRAINT FK_GST_PRY_ID_PROYECTO FOREIGN KEY
(
  ID_PROYECTO 
)
REFERENCES PROYECTO
(
  ID_PROYECTO 
)
ENABLE;

ALTER TABLE HORAS_TRABAJADAS
ADD CONSTRAINT FK_H_TRAB_EMP_ID_EMPLEADO FOREIGN KEY
(
  ID_EMPLEADO 
)
REFERENCES EMPLEADO
(
  ID_EMPLEADO 
)
ENABLE;

ALTER TABLE LINEA_FACTURA
ADD CONSTRAINT LINEA_FACTURA_FACTURA_FK FOREIGN KEY
(
  ID_FACTURA 
)
REFERENCES FACTURA
(
  ID_FACTURA 
)
ENABLE;

ALTER TABLE L_MAT_PROVEEDOR
ADD CONSTRAINT FK_L_MAT_PROV_FACT_ID_FACTURA FOREIGN KEY
(
  ID_FACTURA 
)
REFERENCES LINEA_FACTURA
(
  ID_FACTURA 
)
ENABLE;

ALTER TABLE L_MAT_PROVEEDOR
ADD CONSTRAINT L_MAT_PROVEEDOR_FK1 FOREIGN KEY
(
  CODIGO 
)
REFERENCES MATERIAL
(
  CODIGO 
)
ENABLE;

ALTER TABLE L_SER_PROVEEDOR
ADD CONSTRAINT FK_L_SER_PROV_FACT_ID_FACTURA FOREIGN KEY
(
  ID_FACTURA 
)
REFERENCES LINEA_FACTURA
(
  ID_FACTURA 
)
ENABLE;

ALTER TABLE L_SER_PROVEEDOR
ADD CONSTRAINT FK_L_SER_PROV_SER_CODIGO FOREIGN KEY
(
  CODIGO 
)
REFERENCES SERVICIO
(
  CODIGO 
)
ENABLE;

ALTER TABLE MAT_PROVEEDOR
ADD CONSTRAINT FK_MAT_PROV_MAT_CODIGO FOREIGN KEY
(
  CODIGO 
)
REFERENCES MATERIAL
(
  CODIGO 
)
ENABLE;

ALTER TABLE MAT_PROVEEDOR
ADD CONSTRAINT FK_MAT_PROV_PROV_ID_PROVEEDOR FOREIGN KEY
(
  ID_PROVEEDOR 
)
REFERENCES PROVEEDOR
(
  ID_PROVEEDOR 
)
ENABLE;

ALTER TABLE PROVEEDOR_EMAIL
ADD CONSTRAINT FK_EMAIL_PROV_ID_PROVEEDOR FOREIGN KEY
(
  ID_PROVEEDOR 
)
REFERENCES PROVEEDOR
(
  ID_PROVEEDOR 
)
ENABLE;

ALTER TABLE PROVEEDOR_TELEFONO
ADD CONSTRAINT FK_TEL_PROV_ID_PROVEEDOR FOREIGN KEY
(
  ID_PROVEEDOR 
)
REFERENCES PROVEEDOR
(
  ID_PROVEEDOR 
)
ENABLE;

ALTER TABLE PROV_SERVICIO
ADD CONSTRAINT FK_PROV_SRVC_CODIGO FOREIGN KEY
(
  CODIGO 
)
REFERENCES SERVICIO
(
  CODIGO 
)
ENABLE;

ALTER TABLE PROV_SERVICIO
ADD CONSTRAINT FK_PROV_SRVC_ID_PROVEEDOR FOREIGN KEY
(
  ID_PROVEEDOR 
)
REFERENCES PROVEEDOR
(
  ID_PROVEEDOR 
)
ENABLE;

ALTER TABLE PROYECTO_SUPERVISOR
ADD CONSTRAINT PROYECTO_SUPERVISOR_FK1 FOREIGN KEY
(
  ID_EMPLEADO 
)
REFERENCES EMPLEADO
(
  ID_EMPLEADO 
)
ENABLE;

ALTER TABLE PROYECTO_SUPERVISOR
ADD CONSTRAINT PROYECTO_SUPERVISOR_FK2 FOREIGN KEY
(
  ID_PROYECTO 
)
REFERENCES PROYECTO
(
  ID_PROYECTO 
)
ENABLE;

ALTER TABLE CUENTAS_POR_COBRAR
ADD CONSTRAINT CK_CNT_ESTADO CHECK 
(ESTADO = 'P' OR ESTADO = 'C')
ENABLE;

ALTER TABLE EMPLEADO
ADD CONSTRAINT CK_EMP_FCH_REGISTRO CHECK 
(FECHA_REGISTRO = GETDATE())
ENABLE;

ALTER TABLE EMPLEADO
ADD CONSTRAINT CK_EMP_FCH_ULT_MOD CHECK 
(FECHA_ULT_MOD = GETDATE())
ENABLE;

ALTER TABLE FACTURA
ADD CONSTRAINT CK_FACTURA_FCH CHECK 
(FECHA_FACTURA = GETDATE())
ENABLE;

ALTER TABLE FACTURA
ADD CONSTRAINT CK_FACTURA_ULT_MOD CHECK 
(FECHA_ULT_MOD = GETDATE())
ENABLE;

ALTER TABLE HORAS_TRABAJADAS
ADD CONSTRAINT CK_H_TRAB_ESTADO CHECK 
(ESTADO = 'P' OR ESTADO = 'C')
ENABLE;

ALTER TABLE LINEA_FACTURA
ADD CONSTRAINT CK_L_F_FCH_REGISTRO CHECK 
(FECHA_REGISTRO = GETDATE())
ENABLE;

ALTER TABLE LINEA_FACTURA
ADD CONSTRAINT CK_L_F_FCH_ULT_MOD CHECK 
(FECHA_ULT_MOD = GETDATE())
ENABLE;

ALTER TABLE PROVEEDOR
ADD CONSTRAINT CK_PROV_FCH_REGISTRO CHECK 
(FECHA_REGISTRO = getdate())
ENABLE;

ALTER TABLE PROVEEDOR
ADD CONSTRAINT CK_PROV_FCH_U_MOD CHECK 
(FECHA_ULT_MOD = getdate())
ENABLE;

ALTER TABLE PROVEEDOR_EMAIL
ADD CONSTRAINT CK_EMAIL_PROV_FCH_REGISTRO CHECK 
(FECHA_REGISTRO= GETDATE())
ENABLE;

ALTER TABLE PROVEEDOR_EMAIL
ADD CONSTRAINT CK_EMAIL_PROV_FCH_ULT_MOD CHECK 
(FECHA_ULT_MOD = GETDATE())
ENABLE;

ALTER TABLE PROV_SERVICIO
ADD CONSTRAINT CK_PROV_SRVC_FCH_REGISTRO CHECK 
(FECHA_REGISTRO = GETDATE())
ENABLE;

ALTER TABLE PROV_SERVICIO
ADD CONSTRAINT CK_PROV_SRVC_FCH_ULT_MOD CHECK 
(FECHA_ULT_MOD = GETDATE())
ENABLE;

ALTER TABLE SERVICIO
ADD CONSTRAINT CK_SRVC_FCH_REGISTRO CHECK 
(FECHA_REGISTRO = GETDATE())
ENABLE;

ALTER TABLE SERVICIO
ADD CONSTRAINT CK_SRVC_FCH_ULT_MOD CHECK 
(FECHA_ULT_MOD = GETDATE())
ENABLE;

COMMENT ON COLUMN L_MAT_PROVEEDOR.COSTO_TOTAL IS 'unidad * costo';
